"""Persistent loopback OAuth callback receiver for the built-in Google skills.

The gmail/gcalendar skills authenticate with a Google **Desktop** OAuth client,
which only permits loopback redirect URIs (``http://127.0.0.1:<port>/``).

Historically each ``link`` run started its OWN ephemeral loopback server inside
the short-lived skill subprocess (``InstalledAppFlow.run_local_server``). That
server was gone by the time the user finished consent — the subprocess is
backgrounded/torn down with the agent turn, and in Docker its random port was
never published — so the browser redirect hit a dead port and failed with
``ERR_CONNECTION_REFUSED``.

Instead, ``cremind serve`` runs ONE persistent loopback listener here for the
lifetime of the backend (mirroring how every other OAuth flow — MCP, A2A — uses
the always-running backend rather than a transient server). The skill points its
redirect at this listener; when the user consents Google redirects here, and we
hand the raw authorization response (``code`` + ``state`` + ``scope``) to the
skill via a per-state file under ``<CREMIND_SYSTEM_DIR>/oauth_inbox/``. The skill
then performs the PKCE token exchange itself — the authorization ``code`` is
useless without the ``code_verifier`` the skill holds — so tokens never leave the
machine and cremind-connect is never in the token path.

Binding: in Docker the listener binds ``0.0.0.0`` (``CREMIND_OAUTH_BIND_ADDR``)
and the port is published so the host browser can reach it; on bare metal it
binds ``127.0.0.1``. The redirect the skill advertises always uses ``127.0.0.1``
(a valid Desktop-client loopback that also dodges the Windows ``localhost`` ->
``::1`` resolution that can otherwise refuse an IPv4-only server).
"""
from __future__ import annotations

import os
import re
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse

from app.config.settings import BaseConfig
from app.utils import logger

# The OAuth ``state`` is generated by oauthlib (a URL-safe token). It becomes a
# filename here, so accept only this charset/length and reject anything else —
# this is the guard against path traversal via a crafted ``state``.
_STATE_RE = re.compile(r"^[A-Za-z0-9_-]{8,128}$")

# Drop inbox files older than this so abandoned consent flows don't accumulate.
_INBOX_TTL_S = 600

_server: ThreadingHTTPServer | None = None
_thread: threading.Thread | None = None

_SUCCESS_HTML = (
    b"<!doctype html><html><head><meta charset='utf-8'><title>Cremind</title></head>"
    b"<body style='font-family:sans-serif;text-align:center;padding-top:3rem'>"
    b"<h1>Authentication complete</h1>"
    b"<p>You can close this window and return to Cremind.</p>"
    b"<script>setTimeout(function(){window.close()},2000)</script></body></html>"
)
_ERROR_HTML = (
    b"<!doctype html><html><head><meta charset='utf-8'><title>Cremind</title></head>"
    b"<body style='font-family:sans-serif;text-align:center;padding-top:3rem'>"
    b"<h1>Authentication failed</h1>"
    b"<p>You can close this window and try linking again.</p></body></html>"
)


def oauth_inbox_dir() -> str:
    """Directory where captured authorization responses are dropped for skills."""
    return os.path.join(BaseConfig.CREMIND_SYSTEM_DIR, "oauth_inbox")


def _prune_stale(inbox: str) -> None:
    try:
        now = time.time()
        for name in os.listdir(inbox):
            path = os.path.join(inbox, name)
            try:
                if now - os.path.getmtime(path) > _INBOX_TTL_S:
                    os.remove(path)
            except OSError:
                pass
    except OSError:
        pass


def _write_inbox(state: str, query: str) -> None:
    """Atomically drop the raw authorization-response query for ``state``."""
    inbox = oauth_inbox_dir()
    os.makedirs(inbox, exist_ok=True)
    _prune_stale(inbox)
    dst = os.path.join(inbox, f"{state}.txt")
    tmp = dst + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(query)
    os.replace(tmp, dst)


class _Handler(BaseHTTPRequestHandler):
    # Silence the default per-request stderr logging from BaseHTTPRequestHandler.
    def log_message(self, *args):  # noqa: D401, N802
        return

    def _respond(self, status: int, body: bytes) -> None:
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        try:
            self.wfile.write(body)
        except OSError:
            pass

    def do_GET(self):  # noqa: N802
        parsed = urlparse(self.path)
        # Only the loopback root path is a valid redirect target.
        if parsed.path not in ("", "/"):
            self._respond(404, _ERROR_HTML)
            return
        params = parse_qs(parsed.query)
        state = (params.get("state") or [""])[0]
        if not _STATE_RE.match(state):
            logger.warning("[oauth-loopback] callback with missing/invalid state; ignoring")
            self._respond(400, _ERROR_HTML)
            return
        try:
            _write_inbox(state, parsed.query)
        except OSError as e:  # noqa: BLE001
            logger.error(f"[oauth-loopback] failed to write inbox file: {e}")
            self._respond(500, _ERROR_HTML)
            return
        if "error" in params:
            logger.info(f"[oauth-loopback] consent returned error for state={state[:6]}…")
            self._respond(200, _ERROR_HTML)
        else:
            logger.info(f"[oauth-loopback] captured authorization response for state={state[:6]}…")
            self._respond(200, _SUCCESS_HTML)


def start_oauth_loopback_listener() -> bool:
    """Start the persistent loopback callback listener. Returns ``True`` on success.

    Non-fatal on failure (e.g. the port is already in use): logs a warning and
    returns ``False``. Account linking then falls back to the skill's own
    ephemeral loopback server.
    """
    global _server, _thread
    if _server is not None:
        return True
    bind_addr = BaseConfig.CREMIND_OAUTH_BIND_ADDR or "127.0.0.1"
    port = BaseConfig.CREMIND_OAUTH_CALLBACK_PORT
    try:
        os.makedirs(oauth_inbox_dir(), exist_ok=True)
        srv = ThreadingHTTPServer((bind_addr, port), _Handler)
    except OSError as e:  # noqa: BLE001
        logger.warning(
            f"[oauth-loopback] could not bind {bind_addr}:{port} ({e}); Google "
            "account linking will fall back to an ephemeral loopback server."
        )
        return False
    srv.daemon_threads = True
    t = threading.Thread(target=srv.serve_forever, name="oauth-loopback", daemon=True)
    t.start()
    _server = srv
    _thread = t
    logger.info(
        f"[oauth-loopback] listening on http://{bind_addr}:{port}/ "
        f"(inbox: {oauth_inbox_dir()})"
    )
    return True


def stop_oauth_loopback_listener() -> None:
    """Stop the listener if running. Safe to call when never started."""
    global _server, _thread
    srv, _server = _server, None
    _thread = None
    if srv is not None:
        try:
            srv.shutdown()
            srv.server_close()
        except Exception:  # noqa: BLE001
            logger.exception("[oauth-loopback] error during shutdown")
